services:
  db:
    container_name: railway_system_db
    image: postgres
    environment:
      POSTGRES_USER: bogdanjmk
      POSTGRES_PASSWORD: bogdanjmk1.
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5001:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: